// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -Ivendor/linux-2.6.26-lab126/include -D__KERNEL__ constant_defs.go

package kindleland

const FrameBufferDevice = "/dev/fb/0"

type UpdateMode int

const (
	FxFlash         = UpdateMode(0x14)
	FxUpdatePartial = UpdateMode(0x0)
	FxUpdateFull    = UpdateMode(0x1)
	FxUpdateFast    = UpdateMode(0x2)
	FxUpdateSlow    = UpdateMode(0x3)
)

const FBIOEinkUpdateDisplayFx = 0x46e4
const FBIOEinkUpdateDisplay = 0x46db
const FBIOEinkClearScreen = 0x46e1

// #define FBIO_EINK_UPDATE_DISPLAY            _IO(FBIO_MAGIC_NUMBER, 0xdb) // 0x46db (fx_type)
// #define FBIO_EINK_UPDATE_DISPLAY_AREA       _IO(FBIO_MAGIC_NUMBER, 0xdd) // 0x46dd (update_area_t *)

type UpdateArea struct {
	X1     int32
	Y1     int32
	X2     int32
	Y2     int32
	Fx     int32
	Buffer *uint8
}
