// Code generated by "stringer -type=KeyEventType"; DO NOT EDIT.

package kindleland

import "strconv"

const _KeyEventType_name = "KeyUpKeyDownKeyHold"

var _KeyEventType_index = [...]uint8{0, 5, 12, 19}

func (i KeyEventType) String() string {
	if i < 0 || i >= KeyEventType(len(_KeyEventType_index)-1) {
		return "KeyEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyEventType_name[_KeyEventType_index[i]:_KeyEventType_index[i+1]]
}
