// Code generated by "stringer -type=KeyType"; DO NOT EDIT.

package kindleland

import "strconv"

const _KeyType_name = "KeyDeleteKeyQKeyWKeyEKeyRKeyTKeyYKeyUKeyIKeyOKeyPKeyReturnKeyAKeySKeyDKeyFKeyGKeyHKeyJKeyKKeyLKeyShiftKeyZKeyXKeyCKeyVKeyBKeyNKeyMKeyPeriodKeyAltKeySpaceKeyHomeKeyNextPageLeftKeyPrevPageRightKeySymKeyMenuKeyBackKeyTextKeyNextPageRightKeyPrevPageLeft"

var _KeyType_map = map[KeyType]string{
	14:  _KeyType_name[0:9],
	16:  _KeyType_name[9:13],
	17:  _KeyType_name[13:17],
	18:  _KeyType_name[17:21],
	19:  _KeyType_name[21:25],
	20:  _KeyType_name[25:29],
	21:  _KeyType_name[29:33],
	22:  _KeyType_name[33:37],
	23:  _KeyType_name[37:41],
	24:  _KeyType_name[41:45],
	25:  _KeyType_name[45:49],
	28:  _KeyType_name[49:58],
	30:  _KeyType_name[58:62],
	31:  _KeyType_name[62:66],
	32:  _KeyType_name[66:70],
	33:  _KeyType_name[70:74],
	34:  _KeyType_name[74:78],
	35:  _KeyType_name[78:82],
	36:  _KeyType_name[82:86],
	37:  _KeyType_name[86:90],
	38:  _KeyType_name[90:94],
	42:  _KeyType_name[94:102],
	44:  _KeyType_name[102:106],
	45:  _KeyType_name[106:110],
	46:  _KeyType_name[110:114],
	47:  _KeyType_name[114:118],
	48:  _KeyType_name[118:122],
	49:  _KeyType_name[122:126],
	50:  _KeyType_name[126:130],
	52:  _KeyType_name[130:139],
	56:  _KeyType_name[139:145],
	57:  _KeyType_name[145:153],
	102: _KeyType_name[153:160],
	104: _KeyType_name[160:175],
	109: _KeyType_name[175:191],
	126: _KeyType_name[191:197],
	139: _KeyType_name[197:204],
	158: _KeyType_name[204:211],
	190: _KeyType_name[211:218],
	191: _KeyType_name[218:234],
	193: _KeyType_name[234:249],
}

func (i KeyType) String() string {
	if str, ok := _KeyType_map[i]; ok {
		return str
	}
	return "KeyType(" + strconv.FormatInt(int64(i), 10) + ")"
}
